project:
  type: website

website:
  title: "Julian Granna"
  navbar:
    logo: icon2.png
    left:
      - href: rprojects.qmd
        text: R Projects
      - href: research.qmd
        text: Research and Teaching

format:
  html:
    theme: 
      light: [quartz, custom.scss]
      dark: cyborg
    css: styles.css
    toc: true

editor: visual

